version: '3'

services:
  dbpostgres:
    image: 'postgres:11'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=klubee-db
      - POSTGRES_PORT=5432
    volumes:
      - /var/lib/postgresql/data
    
  # api:
  #   build:
  #     context: ./backend
  #     dockerfile: ./DockerFile
  #   links:
  #       - dbpostgres
  #   ports:
  #     - '3333:3333'
  #   volumes: 
  #     - ./backend:/usr/src/app
  #   depends_on:
  #     - dbpostgres
  #   command: npm run dev  