version: '3'

services:
  dbmongo:
    image: 'mongo'
    ports:
      - '27018:27017'
  dbpostgres:
    image: 'postgres:11'
    ports:
      - '5433:5432'
    volumes:
      - ./data-postgresql:/var/lib/postgresql/data 
    
  api:
    build:
      context: ./backend
      dockerfile: ./DockerFile
    links:
        - dbmongo
        - dbpostgres
    ports:
      - '3333:3333'
    volumes: 
      - ./backend:/usr/src/app
    depends_on:
      - dbmongo
      - dbpostgres
    command: npm run dev  